// <auto-generated />
using System;
using BlazorBase.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorBase.Infrastructure.Migrations
{
    [DbContext(typeof(BlazorBaseContext))]
    [Migration("20221228072825_CreateM_ログインユーザー")]
    partial class CreateM_ログインユーザー
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorBase.Infrastructure.Entities.M_ログインユーザーDbEntity", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserName");

                    b.ToTable("M_ログインユーザー", (string)null);
                });

            modelBuilder.Entity("BlazorBase.Infrastructure.Entities.M_事業所DbEntity", b =>
                {
                    b.Property<string>("事業所番号")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("事業所名")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("事業所名カナ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("住所")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("定員規模")
                        .HasColumnType("int");

                    b.Property<bool>("就労継続A型減免有無")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("登録日")
                        .HasColumnType("datetime2");

                    b.Property<string>("郵便番号")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("電話番号")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("事業所番号");

                    b.ToTable("M_事業所", (string)null);
                });

            modelBuilder.Entity("BlazorBase.Infrastructure.Entities.M_事業所明細DbEntity", b =>
                {
                    b.Property<string>("事業所番号")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("連番")
                        .HasColumnType("int");

                    b.Property<string>("サービス提供単位番号")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("単位数単価")
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("多機能型用件")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("定員")
                        .HasColumnType("int");

                    b.Property<string>("施設名")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("種類コード")
                        .HasColumnType("bit");

                    b.Property<string>("種類区分")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("事業所番号", "連番");

                    b.ToTable("M_事業所明細", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
